* e建筑成员邀请功能概述
核心思想参考github（全世界程序员的版本管理系统，其文件协同操作流程经过全世界程序员的验证，并且已经实现商业化），以项目创建者为核心，以项目成员为辐射点
** e建筑成员邀请功能设想
 1. 在邀请页面，填入被邀请成员时，如果填入用户名称为非注册用户，直接在后台注册，并发送随机密码给该用户地址（可以快速积累用户）
 2. 被邀请成员登陆e建筑账户后，直接操作“接受邀请”或“拒绝邀请”选项，接受后，可以直接进入项目空间，但只能浏览文件，不可以进行任何编辑操作。
 3. 被邀请用户可以发送"申请成为管理员"给项目空间所有者
 4. 成为“管理员”后，用户可以进行各种编辑操作，但是编辑完成后，要给项目所有者“确认”更改，由项目所有者最终决定是否同意更改。
 5. 项目所有者具有最高决定权，这样就没有对每个文件分配权限的复杂操作。
** e建筑现有成员邀请功能
 1. 在邀请页面，填入被邀请成员时，如果填入用户名称为非注册用户，直接提示非注册用户
 2. 被邀请成员登陆e建筑账户后，没有经过确认接受邀请，在点击项目空间后，提示非管理员权限
 3. 成为管理员后，..............（有BUG，现在还没有办法测试）
** 广联云现有成员邀请功能
 1. 在邀请页面，填入被邀请成员时，如果填入用户名称为非注册用户，直接在后台注册，并发送随机密码给该用户地址。
 2. 被邀请成员登陆广联云账户后，直接操作”接受邀请“或”拒绝邀请“，接受后可以直接进入项目空间，但是该空间为空。


* e建筑网站UI
 网站作为展示e建筑产品的平台，应力求简洁大气，方便用户导航，提高登陆、注册、下载等操作的用户体验
 1. 网站导航栏尽量醒目，做到让用户点击导航栏而不用鼠标滚轮上下查看
 2. 用户登录注册尽量方便，减少用户输入内容。
 3. 用户下载安装各个平台安装包要方便快捷。
 4. 网站内容要突出展示核心卖点。


*  e建筑现有功能
** 文件存储
** 项目邀请（协作）
** 文件预览
* 广联云现有功能
** 文件存储
** 项目邀请
** 任务分发
** 文件预览

* e建筑与广联云的差异化
建筑软件要做就做第一，做第二是没有任何意义(市场太小，局限于建筑行业）。所以我们一方面要汲取各方好的东西，但同时要与对手形成差异化。
** 网站UI尽量借鉴广联达，
 网站UI尽量借鉴广联达的，他们应该是有这方面的专业人才，经过思考做出来的，在我们没有专门人员负责这块情况下，借鉴广联达是个好主意，
雷军说过，一切照抄苹果的都是对的，支付宝与微信的APP某些active一模一样，同时，凡是windows系统的应用程序都抄微软，所以我们不
用考虑怕借鉴广联达的界面，我们不靠这些取胜。
** 产品功能上优于广联达
 网站功能上，广联云的协同不一定是最好的，而我们一方面可以参考广联云的好的方面，但同时对于软件行业的协同也可以参考（因为软件行业的协同是最成功的），
这样形成差异化，提升我们的优势。
1. 协作流程，去掉权限分配的复杂操作，简化为以项目创建者为核心（对于项目空间中文件改、删、添加操作，最终由项目创建者决定），以项目成员为参与者（可以进行修改、添加、删除操作，但最终由项目所有者决定是否采纳）
2. 版本控制，git的版本控制已经非常成熟，但是有个前提，他的版本控制的是纯文本，不管是代码还是文字都必须要求是纯文本形式。而对于我们建筑行业文件，如RVT,IFC,DWG全世界都还没有办法做到真正意义的版本控制，但是我们可以参考git的一些思想
3. 讨论功能，现在广联达是有个评论功能，如果参考github，针对项目空间文件的疑问是可以开issue，每一个项目参与者都可以开，然后其他项目成员可以回答这个issue。可以对比两种方式的优劣。
4. 任务分发功能，广联云现在有这个功能，我们没有。但是我觉得没有是正确的，一方面任务分发功能没有哪一家做的特别好，另一方面，我们的e建筑就是文件管理，把我们这一块做好已经不容易了。


